async_logger: make USDT with Folly library actually work
The BPF JIT was failing to compile the USDT probe:

/virtual/main.c:9:73: error: unknown type name 'int256_t'; did you mean 'int16_t'?
  { u64 __addr = ctx->r14 + -64; __asm__ __volatile__("": : :"memory"); int256_t __res = 0x0; bpf_probe_read_user(&__res, sizeof(__res), (void *)__addr); *((int256_t *)dest) = __res; }
                                                                        ^~~~~~~~
                                                                        int16_t

Running Facebook's latency.py with verbose output showed that the
problem occurred in evaluation of the generated code:

__attribute__((always_inline))
static __always_inline int _bpf_readarg_trace_operation_start_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(int64_t)) return -1;
  { u64 __addr = ctx->bp + -128; __asm__ __volatile__("": : :"memory"); int64_t __res = 0x0; bpf_probe_read_user(&__res, sizeof(__res), (void *)__addr); *((int64_t *)dest) = __res; }
  return 0;
}

Comparison of the output from "readelf -n" showed differents in the
"Arguments" field:

$ readelf -n async_logger_improved
  stapsdt              0x00000051       NT_STAPSDT (SystemTap probe descriptors)
    Provider: async_logger_improved
    Name: operation_start
    Location: 0x000000000001f117, Base: 0x0000000000000000, Semaphore: 0x0000000000000000
    Arguments: -8@%rdx -32@(%rax)

$ readelf -n examples/usdt_sample/build/usdt_sample_lib1/libusdt_sample_lib1.so
  stapsdt              0x00000055       NT_STAPSDT (SystemTap probe descriptors)
    Provider: usdt_sample_lib1
    Name: operation_start
    Location: 0x000000000000e6f6, Base: 0x0000000000000000, Semaphore: 0x0000000000000000
    Arguments: -8@-128(%rbp) -8@-136(%rbp)

The Facebook code showed that both args were of size 8.  A size 32
would need an int256_t if size 8 required u64.

The fix turned out to be providing basic_string's as the final
parameter passed to the FOLLY_SDT macro rather than std::string's.